### ISSUE TITLE
按文档配置好混淆规则，开启混淆后，调用人脸识别就出现 fast json 栈溢出。请问能帮忙查一查原因吗？

### ISSUE THREAD

**Issue by ly20050516** [alibaba/MNNKit#30]
一、问题：如标所述，问题栈如下。
at com.alibaba.fastjson.JSON.toJSON(JSON.java:852)
        at com.alibaba.fastjson.JSON.toJSON(JSON.java:932)
        at com.alibaba.fastjson.JSON.toJSON(JSON.java:852)
        at com.alibaba.fastjson.JSON.toJSON(JSON.java:932)
        at com.alibaba.fastjson.JSON.toJSON(JSON.java:852)
        at com.alibaba.fastjson.JSON.toJSON(JSON.java:932)
        at com.alibaba.fastjson.JSON.toJSON(JSON.java:852)
        at com.alibaba.fastjson.JSON.toJSON(JSON.java:932)
        at com.alibaba.fastjson.JSON.toJSON(JSON.java:852)
        at com.alibaba.fastjson.JSON.toJSON(JSON.java:932)
        at com.alibaba.fastjson.JSON.toJSON(JSON.java:852)
        at com.alibaba.android.mnnkit.monitor.MNNMonitor.a(SourceFile:324)
        at com.alibaba.android.mnnkit.monitor.MNNMonitor.loadCommit(SourceFile:258)
        at com.alibaba.android.mnnkit.actor.FaceDetector$1.run(SourceFile:132)
        at java.lang.Thread.run(Thread.java:919)
二、环境
编译工具：
Android studio 4.0 / Android Gradle 3.5.0 / Gralde 5.4.1

三、混淆规则已按官方文档配置如下：
# mnnkit
-dontwarn com.alibaba.android.mnnkit.**
-keep class com.alibaba.android.mnnkit.**{*;}

-ignorewarnings
-keep class * {
    public private *;
}

**Comment by ly20050516** [comment]
与其他的 proguard 配置冲突导致的，已解决，谢谢

**Comment by LuckyZhang12** [comment]
@ly20050516 还记得跟哪个配置冲突了吗？ 我也碰到了这个问题
